### ISSUE TITLE
Add github workflow to build and publish docker images in docker hub

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#493]
See #491 and #492

Add a github workflow to build and publish both docker images in docker hub.

**Comment by julie-sullivan** [comment]
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
Running on `create` now, but should use `release` in production.

**Comment by julie-sullivan** [comment]
```
 Login to dockerhub0s

Run docker login -u *** -p ***
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Login Succeeded
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

Should be okay because these VMs are not accessible and thrown away?

**Comment by julie-sullivan** [comment]
Each VM has:

```
    2 core CPUs
    7 GB of RAM memory
    14 GB of SSD disk space
```

**Comment by julie-sullivan** [comment]
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits
2000 minutes per month.

**Comment by julie-sullivan** [comment]
Maven is working:

```
 [INFO] Downloading from ossrh: https://oss.sonatype.org/content/repositories/snapshots/org/opencb/cellbase/cellbase-client/maven-metadata.xml
[INFO] Downloaded from ossrh: https://oss.sonatype.org/content/repositories/snapshots/org/opencb/cellbase/cellbase-client/maven-metadata.xml (674 B at 19 kB/s)
[INFO] Uploading to ossrh: https://oss.sonatype.org/content/repositories/snapshots/org/opencb/cellbase/cellbase-client/5.0.0-SNAPSHOT/maven-metadata.xml
[INFO] Uploaded to ossrh: https://oss.sonatype.org/content/repositories/snapshots/org/opencb/cellbase/cellbase-client/5.0.0-SNAPSHOT/maven-metadata.xml (829 B at 5.6 kB/s)
```

**Comment by julie-sullivan** [comment]
javadoc action is updating gh-pages as expected. However, what is on the gh-pages branch and what's available via the url (http://opencb.github.io/cellbase/apidocs/) does not match. 

Specifically we renamed Species to be [SpeciesUtils](https://github.com/opencb/cellbase/blob/gh-pages/apidocs/org/opencb/cellbase/lib/SpeciesUtils.html) . That's in github but not in the hosted javadocs. 

One user reported that it might be a timezone issue?

**Comment by julie-sullivan** [comment]
https://github.com/opencb/cellbase/blob/next/.github/workflows/main.yml#L31
.github/workflows/main.yml:31
```
    - name: Export IOTCL for GPG
```
Check if this is needed. If so, add to release.yml

**Comment by julie-sullivan** [comment]
independent actions that will allow jobs to be run in parallel
```
name: CellBase Release

on:

  push:

    tags:

    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        mongodb-version: ["4.2"]

    steps:

    - uses: actions/checkout@v1

    - name: Set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Launch MongoDB 

      run: sudo docker run --name mongo -d -p 27017:27017 mongo:${{ matrix.mongodb-version }}

    - name: Build with Maven

      run: mvn -T 2 clean install

  deploy_maven:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - uses: actions/checkout@v1

    - name: Set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Release Maven package

      uses: samuelmeuli/action-maven-publish@v1

      with:

        gpg_private_key: ${{ secrets.MAVEN_PRIVATE_KEY }}

        gpg_passphrase: ${{ secrets.MAVEN_PASSPHRASE }}

        nexus_username: ${{ secrets.MAVEN_NEXUS_USER }}

        nexus_password: ${{ secrets.MAVEN_NEXUS_PASSWORD }}

  docker:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - uses: actions/checkout@v1

    - name: Set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Build with Maven

      run: mvn -T 2 clean install -DskipTests

    - name: Login to dockerhub

      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Get the version

      id: get_version

      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and publish Docker images to DockerHub

      run: ./cellbase-app/app/cloud/docker/docker-build.sh push ${{ steps.get_version.outputs.VERSION }}

  javadocs:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - uses: actions/checkout@v1

    - name: Set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Generate Javadocs

      run: mvn javadoc:aggregate

    - name: Deploy Javadocs

      uses: JamesIves/github-pages-deploy-action@releases/v3

      with:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        BASE_BRANCH: next # The branch the action should deploy from.

        BRANCH: gh-pages # The branch the action should deploy to.

        FOLDER: target/site # The folder the action should deploy.

```
