### ISSUE TITLE
hsapiens is a shortname, id, and species in the data model. Could we merge?

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#503]
`hsapiens` is the `id` in the SpeciesConfiguration and configuration file:

```
# configuration.yml
species:
 vertebrates:
  - id: hsapiens
```

But in the [core/common](https://github.com/opencb/cellbase/blob/next/cellbase-core/src/main/java/org/opencb/cellbase/core/common/Species.java#L34) `hsapiens` is called the `shortName` and `species`. Could we merge?
